name: goreleaser

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}

      - name: Trigger Repository Update
        run: |
          curl --request POST \
               --form token=${{ secrets.GITLAB_TRIGGER_TOKEN }} \
               --form ref=main \
               --form "variables[VERSION]=${{ github.ref_name }}" \
               "https://gitlab.com/api/v4/projects/afonsodemori%2Fpackages/trigger/pipeline"
